<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260618101927 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Multi-tenant: create gym tables, add gym_id to existing entities, migrate existing data';
    }

    public function up(Schema $schema): void
    {
        // 1. Create new tables
        $this->addSql('CREATE TABLE gym (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, gym_owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7F27DBED989D9B62 ON gym (slug)');
        $this->addSql('CREATE INDEX IDX_7F27DBED309C9069 ON gym (gym_owner_id)');
        $this->addSql('CREATE TABLE gym_owner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_73EFF41EE7927C74 ON gym_owner (email)');
        $this->addSql('CREATE TABLE gym_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, plan VARCHAR(20) NOT NULL, trial_ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, amount INT NOT NULL, fedapay_transaction_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, gym_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_95E34CEEBD2F03 ON gym_subscription (gym_id)');
        $this->addSql('ALTER TABLE gym ADD CONSTRAINT FK_7F27DBED309C9069 FOREIGN KEY (gym_owner_id) REFERENCES gym_owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gym_subscription ADD CONSTRAINT FK_95E34CEEBD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // 2. Add gym_id columns (nullable) to existing tenant entities
        $this->addSql('ALTER TABLE category ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_64C19C1BD2F03 ON category (gym_id)');
        $this->addSql('ALTER TABLE checkin ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE checkin ADD CONSTRAINT FK_E1631C91BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_E1631C91BD2F03 ON checkin (gym_id)');
        $this->addSql('ALTER TABLE client ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_C7440455BD2F03 ON client (gym_id)');
        $this->addSql('ALTER TABLE "order" ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_F5299398BD2F03 ON "order" (gym_id)');
        $this->addSql('ALTER TABLE payment ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DBD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_6D28840DBD2F03 ON payment (gym_id)');
        $this->addSql('ALTER TABLE product ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADBD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_D34A04ADBD2F03 ON product (gym_id)');
        $this->addSql('ALTER TABLE subscription ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_A3C664D3BD2F03 ON subscription (gym_id)');
        $this->addSql('ALTER TABLE "user" ADD gym_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_8D93D649BD2F03 ON "user" (gym_id)');

        // 3. Insert default GymOwner
        $hashedPassword = password_hash('ChangeMe2026!', PASSWORD_BCRYPT);
        $this->addSql("INSERT INTO gym_owner (name, email, password, phone, created_at)
            VALUES ('Kinetic Pulse Default', 'admin@kineticpulse.com', '{$hashedPassword}', NULL, NOW())");

        // 4. Insert default Gym
        $this->addSql("INSERT INTO gym (gym_owner_id, name, slug, created_at)
            VALUES ((SELECT id FROM gym_owner WHERE email = 'admin@kineticpulse.com'), 'Kinetic Pulse', 'kinetic-pulse-default', NOW())");

        // 5. Insert default GymSubscription (active for 1 year)
        $this->addSql("INSERT INTO gym_subscription (gym_id, status, plan, trial_ends_at, starts_at, ends_at, amount, created_at)
            VALUES (
                (SELECT id FROM gym WHERE slug = 'kinetic-pulse-default'),
                'active', 'monthly', NOW(), NOW(), NOW() + INTERVAL '1 year', 15000, NOW()
            )");

        // 6. Update all existing rows to point to the default gym
        $defaultGymId = '(SELECT id FROM gym WHERE slug = \'kinetic-pulse-default\')';
        $tables = ['category', 'checkin', 'client', '"order"', 'payment', 'product', 'subscription', '"user"'];
        foreach ($tables as $table) {
            $this->addSql("UPDATE {$table} SET gym_id = {$defaultGymId} WHERE gym_id IS NULL");
        }

        // 7. Make gym_id NOT NULL on all tenant tables
        foreach ($tables as $table) {
            $this->addSql("ALTER TABLE {$table} ALTER COLUMN gym_id SET NOT NULL");
        }
    }

    public function down(Schema $schema): void
    {
        $tables = ['category', 'checkin', 'client', '"order"', 'payment', 'product', 'subscription', '"user"'];
        $cleanNames = ['category', 'checkin', 'client', 'order', 'payment', 'product', 'subscription', 'user'];

        $fkConstraints = [
            'category' => 'FK_64C19C1BD2F03',
            'checkin' => 'FK_E1631C91BD2F03',
            'client' => 'FK_C7440455BD2F03',
            '"order"' => 'FK_F5299398BD2F03',
            'payment' => 'FK_6D28840DBD2F03',
            'product' => 'FK_D34A04ADBD2F03',
            'subscription' => 'FK_A3C664D3BD2F03',
            '"user"' => 'FK_8D93D649BD2F03',
        ];

        $idxNames = [
            'category' => 'IDX_64C19C1BD2F03',
            'checkin' => 'IDX_E1631C91BD2F03',
            'client' => 'IDX_C7440455BD2F03',
            '"order"' => 'IDX_F5299398BD2F03',
            'payment' => 'IDX_6D28840DBD2F03',
            'product' => 'IDX_D34A04ADBD2F03',
            'subscription' => 'IDX_A3C664D3BD2F03',
            '"user"' => 'IDX_8D93D649BD2F03',
        ];

        foreach ($tables as $table) {
            $this->addSql("ALTER TABLE {$table} DROP CONSTRAINT {$fkConstraints[$table]}");
            $this->addSql("DROP INDEX {$idxNames[$table]}");
            $this->addSql("ALTER TABLE {$table} DROP gym_id");
        }

        $this->addSql('ALTER TABLE gym_subscription DROP CONSTRAINT FK_95E34CEEBD2F03');
        $this->addSql('ALTER TABLE gym DROP CONSTRAINT FK_7F27DBED309C9069');
        $this->addSql('DROP TABLE gym_subscription');
        $this->addSql('DROP TABLE gym');
        $this->addSql('DROP TABLE gym_owner');
    }
}
