<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260730100259 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create wallet system: gym_wallet, wallet_transaction, withdrawal_request, webhook_event';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE gym_wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, balance_available INT NOT NULL, balance_pending INT NOT NULL, balance_pending_withdrawal INT NOT NULL, total_earned INT NOT NULL, currency VARCHAR(10) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, gym_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF681D79BD2F03 ON gym_wallet (gym_id)');
        $this->addSql('CREATE TABLE wallet_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, amount INT NOT NULL, balance_before INT NOT NULL, balance_after INT NOT NULL, reference VARCHAR(255) DEFAULT NULL, description VARCHAR(500) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, gym_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_wallet_tx_gym ON wallet_transaction (gym_id)');
        $this->addSql('CREATE TABLE webhook_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fedapay_event_id VARCHAR(255) NOT NULL, event_type VARCHAR(50) NOT NULL, payload JSON NOT NULL, status VARCHAR(20) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WEBHOOK_EVENT_ID ON webhook_event (fedapay_event_id)');
        $this->addSql('CREATE TABLE withdrawal_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, mobile_money_number VARCHAR(20) NOT NULL, mobile_money_operator VARCHAR(10) NOT NULL, status VARCHAR(20) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fedapay_transfer_id VARCHAR(255) DEFAULT NULL, rejection_reason VARCHAR(500) DEFAULT NULL, admin_notes TEXT DEFAULT NULL, gym_id INT NOT NULL, processed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E56F6D7BD2F03 ON withdrawal_request (gym_id)');
        $this->addSql('CREATE INDEX IDX_5E56F6D72FFD4FD3 ON withdrawal_request (processed_by_id)');
        $this->addSql('ALTER TABLE gym_wallet ADD CONSTRAINT FK_DF681D79BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet_transaction ADD CONSTRAINT FK_7DAF972BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE withdrawal_request ADD CONSTRAINT FK_5E56F6D7BD2F03 FOREIGN KEY (gym_id) REFERENCES gym (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE withdrawal_request ADD CONSTRAINT FK_5E56F6D72FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES "user" (id)');

        // Create wallet for each existing gym
        $this->addSql("INSERT INTO gym_wallet (gym_id, balance_available, balance_pending, balance_pending_withdrawal, total_earned, currency)
            SELECT id, 0, 0, 0, 0, 'XOF' FROM gym
            WHERE id NOT IN (SELECT gym_id FROM gym_wallet)");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE gym_wallet DROP CONSTRAINT FK_DF681D79BD2F03');
        $this->addSql('ALTER TABLE wallet_transaction DROP CONSTRAINT FK_7DAF972BD2F03');
        $this->addSql('ALTER TABLE withdrawal_request DROP CONSTRAINT FK_5E56F6D7BD2F03');
        $this->addSql('ALTER TABLE withdrawal_request DROP CONSTRAINT FK_5E56F6D72FFD4FD3');
        $this->addSql('DROP TABLE gym_wallet');
        $this->addSql('DROP TABLE wallet_transaction');
        $this->addSql('DROP TABLE webhook_event');
        $this->addSql('DROP TABLE withdrawal_request');
    }
}
